### ISSUE TITLE
BiocManager attached on start up

### ISSUE THREAD

**Issue by lgatto** [Bioconductor/bioconductor_docker#12]
I saw that `BiocManager` is added to the list of [packages that are attached](https://github.com/Bioconductor/bioconductor_docker/blob/master/Dockerfile#L154) on start up. Is there a reason for this? I was initially confused that `version` didn't return `base::version` in a clean session.

**Comment by nturaga** [comment]
Yes, I suppose this is because we prefer BiocManager as the default method for installing packages, and it is installed in the docker image by default.

**Comment by lgatto** [comment]
May be I'm missing something, but the installation functions `install.packages()` and `BiocManager::install()` can't be confused.

**Comment by mtmorgan** [comment]
One positive side effect of attaching BiocManager is the modest banner
```
Bioconductor version 3.13 (BiocManager 1.30.10), ?BiocManager::install for help
>
```
when the image starts. It's also possible to avoid attaching BiocManager with the appropriate command line argument, e.g.,
```
$ docker run -it --rm bioconductor/bioconductor_docker:devel R --vanilla
```
But generally I think that BiocManager should be loaded but not attached -- `requireNamespace("BiocManager", quietly=TRUE)`.

**Comment by nturaga** [comment]
@lgatto I believe this issue has been resolved after Martin's commit to BiocManager correct? 

Please close the issue if you think that is correct? If not, I can look into it some more.
