### ISSUE TITLE
Link to localhost in Documentation Gives SSL Error

### ISSUE THREAD

**Issue by const-ae** [Bioconductor/bioconductor_docker#13]
Hi Nitesh,

I just played around with the Docker containers to reproduce an error. Thank you very much for providing those, they make it much easier to reproduce problems that appear on other machines.

In the Quick Start section of the [Docker Containers for Bioconductor](https://www.bioconductor.org/help/docker/) page, it is suggested to go to `https://localhost:8787`. However on my machine, I get an ERR_SSL_PROTOCOL_ERROR which is particularly confusing because the site looks very similar to a page if the application wasn't running:

![image](https://user-images.githubusercontent.com/5359014/82589375-59156800-9b9c-11ea-9326-d3b31c6fd15a.png)
 
The error goes away if you go to the standard http page at `http://localhost:8787`. 

Best, Constantin

**Comment by nturaga** [comment]
I am closing this issue. I've updated the documentation. Thanks, @const-ae.

**Comment by const-ae** [comment]
Great, always happy to help :)
