### ISSUE TITLE
rocker version for bioc-devel

### ISSUE THREAD

**Issue by lwaldron** [Bioconductor/bioconductor_docker#14]
In the spirit of building against development software, perhaps this should instead use `rocker/r-ver:devel`? R 4.0.0 is now a couple months old. I realize this will mean frequent large docker pulls, but maybe it could just be done e.g. weekly? Or, on each new x.y.z "z" release?
https://github.com/Bioconductor/bioconductor_docker/blob/9f18f368a5575c465992d44100af393d292cc9e3/Dockerfile#L2

**Comment by nturaga** [comment]
@lwaldron https://github.com/rocker-org/rocker-versioned2/pull/70 i've issued a PR to rocker. I hope this will be merged and I can have a new image out by end of the day

**Comment by nturaga** [comment]
@lwaldron I think this issue has been resolved.
