### ISSUE TITLE
Problems with packagemanager.rstudio.com

### ISSUE THREAD

**Issue by lwaldron** [Bioconductor/bioconductor_docker#15]
Given the numerous dependency problems we're seeing on #biocworkshopbook (igraph, Rcpp) with rstudio binaries, it seems our Docker image shouldn't be using the packagemanager.rstudio.com mirror by default, and that `options(repos = c(CRAN = 'https://cran.r-project.org'))` would be a safer default. 

Currently:

```
$ docker run -it bioconductor/bioconductor_docker:devel Rscript -e "BiocManager::repositories()"
Bioconductor version 3.12 (BiocManager 1.30.10), ?BiocManager::install for help
                                                        BioCsoft 
                   "https://bioconductor.org/packages/3.12/bioc" 
                                                         BioCann 
        "https://bioconductor.org/packages/3.12/data/annotation" 
                                                         BioCexp 
        "https://bioconductor.org/packages/3.12/data/experiment" 
                                                   BioCworkflows 
              "https://bioconductor.org/packages/3.12/workflows" 
                                                            CRAN 
"https://packagemanager.rstudio.com/all/__linux__/bionic/latest" 
```

**Comment by lwaldron** [comment]
Or alternatively, and probably even better, would be to ensure that the bioconductor_docker container is compatible with the rstudio binary package manager.

**Comment by lwaldron** [comment]
This is now addressed in the tag `bioconductor/bioconductor_docker:bioc2020.1`. Are there drawbacks to making the same change on `:RELEASE_3_11` and `:devel`? Or are the mixed-C-version problems resolved anyways?

```
$ docker run -it bioconductor/bioconductor_docker:bioc2020.1 Rscript -e "BiocManager::repositories()"
Bioconductor version 3.12 (BiocManager 1.30.10), ?BiocManager::install for help
                                                BioCsoft 
           "https://bioconductor.org/packages/3.12/bioc" 
                                                 BioCann 
"https://bioconductor.org/packages/3.12/data/annotation" 
                                                 BioCexp 
"https://bioconductor.org/packages/3.12/data/experiment" 
                                           BioCworkflows 
      "https://bioconductor.org/packages/3.12/workflows" 
                                                    CRAN 
                            "https://cran.r-project.org" 
```

**Comment by mtmorgan** [comment]
We have opted to produce the images using the CRAN settings inherited from the rocker image, i.e., RSPM. The convenience of fast installation seems to greatly outweigh the cost of bug-fixes as incompatibilities are discovered or introduced. Individual deployments may choose to override the choice by creating a derived image that installs from CRAN, or choses a 'last known good' RSPM date.
