### ISSUE TITLE
Update `latest` version to be the same as `RELEASE_3_13`

### ISSUE THREAD

**Issue by nuno-agostinho** [Bioconductor/bioconductor_docker#29]
Looking at [bioconductor/bioconductor_docker](https://hub.docker.com/r/bioconductor/bioconductor_docker/tags) in DockerHub, we can see a discrepancy between push dates for different image versions:
* [latest](https://hub.docker.com/layers/bioconductor/bioconductor_docker/latest/images/sha256-37e72eded9c113cffaf36a2d3740e106b2f923c1cc50cb970f0fb222cd34167e?context=explore) was last pushed 5 months ago (and still contains Bioconductor 3.12)
* [RELEASE_3_13](https://hub.docker.com/layers/bioconductor/bioconductor_docker/RELEASE_3_13/images/sha256-5e0a317fc4e84570483603b1fe0c1b612358dfa2bc0b3d4f29d2460b2f642c55?context=explore) was pushed 16 hours ago
* [RELEASE_3_12](https://hub.docker.com/layers/bioconductor/bioconductor_docker/RELEASE_3_12/images/sha256-e50e0a06d1af66459408d8e11708c2bc79735e3f10aaef325c7359625311c704?context=explore) was released 1 month ago (so `latest` isn't even up-to-date compared to `RELEASE_3_12`...)

I always use the `latest` tag but it needs to be kept updated with the others. Could the `latest` tag somehow be automatically built to avoid such issues in the future? Thank you!

**Comment by nturaga** [comment]
Done.

**Comment by nuno-agostinho** [comment]
Thank you!! 😊
