### ISSUE TITLE
Conflicting definitions of "devel"/"release" between actual Bioconductor and bioconductor_docker

### ISSUE THREAD

**Issue by bschilder** [Bioconductor/bioconductor_docker#37]
Unless I'm missing something, there appears to be a lag between when Bioconductor changes the previous devel to become the current release (3.14 as of today), and when the bioconductor/bioconductor_docker container is updated (it currently lists 3.14 as the devel and 3.13 as the release, which is no longer true).
https://hub.docker.com/layers/bioconductor/bioconductor_docker/devel/images/sha256-5edc02a68f1bbee9db21950b95c133aaab97e15781d3cc1690fed41b3689c2d2?context=explore

This causes (GitHub Action) workflows that depend on harmonized devel/release naming schemes across Bioconductor and bioconductor_docker to break. 

How long of a delay is there between when a new version of Bioconductor is released and when this bioconductor_docker is updated? Is this something that is currently automated?

**Comment by mblue9** [comment]
Hi reading above, should a docker image for RELEASE_3_14 be available here now https://hub.docker.com/r/bioconductor/bioconductor_docker/tags ?

Can only see RELEASE_3_13 and devel which uses 3.15. Be great to get 3.14 for a workshop we have on Monday, actions currently failing due to having no 3.14 Docker available https://github.com/tidytranscriptomics-workshops/rpharma2021_tidytranscriptomics/actions

**Comment by nturaga** [comment]
It's available now. Please check.

**Comment by nturaga** [comment]
@mblue9 Let me know if it worked?

**Comment by mblue9** [comment]
Trying it now & looks like it's working. Thanks a lot @nturaga !!

**Comment by LiNk-NY** [comment]
Hi Brian, @bschilder 
Regarding your note here: https://github.com/marketplace/actions/rworkflows Acknowledgements > Details 
"Often" is an overstatement. The devel container does take a day or two to get updated _immediately_ after the release. Our updates are increasingly automated thanks to Alex @almahmoud 
Throughout the rest of the six month period, the devel container corresponds to the devel version of Bioconductor.

**Comment by bschilder** [comment]
> Hi Brian, @bschilder Regarding your note here: https://github.com/marketplace/actions/rworkflows Acknowledgements > Details "Often" is an overstatement. The devel container does take a day or two to get updated _immediately_ after the release. Our updates are increasingly automated thanks to Alex @almahmoud Throughout the rest of the six month period, the devel container corresponds to the devel version of Bioconductor.

I was referring to the lag after updates, but I can clarify in the description. Great to hear improvements in automation and checking are happening! Thanks for the continued efforts.

**Comment by LiNk-NY** [comment]
Thanks for the clarification.
The lag is due to the release events schedule and the actual time it takes to update them. The containers get updated post-release.

**Comment by bschilder** [comment]
> The lag is due to the release events schedule and the actual time it takes to update them. The containers get updated post-release.

The note now reads:
> **NOTE**: Whenever a new version of Bioconductor is released, 
the `bioconductor/bioconductor_docker` container will often lag behind the actual Bioconductor releases 
for up to several days, due to the time it takes to update the container.
This means that sometimes "devel" in `Bioconductor/bioconductor_docker` is actually referring to the "release" 
version of Bioconductor. See this [Issue](https://github.com/Bioconductor/bioconductor_docker/issues/37) 
for details. 

Does that seem accurate to you?

**Comment by LiNk-NY** [comment]
Looks good. The second to last sentence might going into too much detail but you could say that during that period, `devel` still refers to the previous release's `devel` which is the current `release` version (if this info is necessary).
