### ISSUE TITLE
Issue running my bioc docker using volumes

### ISSUE THREAD

**Issue by risserlin** [Bioconductor/bioconductor_docker#4]
volume was created and used with previous version of bioc container (bioconductor/release_core2:R3.6.0_Bioc3.9)

When  I change my docker from bioconductor/release_core2:R3.6.0_Bioc3.9 to bioconductor/bioconductor_docker:RELEASE_3_10, build my image and then try and run my image the run command seems to hang for a long time.  After a few minutes it starts spitting out the following error messages for my files:
chown: changing ownership of '/home/bioc/data/gsva_randomizations_GDC_subset_origoverlap/SYNDECAN-3-MEDIATED SIGNALING EVENTS%PATHWAY INTERACTION DATABASE NCI-NATURE CURATED DATA%SYNDECAN-3-MEDIATED SIGNALING EVENTS.txt': Input/output error

The run command that I am using:
docker run -e PASSWORD=password --rm -p 8787:8787  -v /path/to/largeish/directory/created/with/previous/bioc/container:/home/bioc  --add-host "localhost:###.###.###.###" em_base_image

My docker image is available on docker hub
https://hub.docker.com/repository/docker/risserlin/em_base_image

**Comment by nturaga** [comment]
Hi @risserlin please see https://github.com/Bioconductor/bioconductor_docker/commit/3d4b0212129f9de1522152d3e562513b08384506. That should fix the issue.
