### ISSUE TITLE
Unable to install additional Bioconductor packages.

### ISSUE THREAD

**Issue by usu-imeg** [Bioconductor/bioconductor_docker#65]
Hi, I am installing additional new bioconductor packages [ BiocManager::install() ] while running this Docker image and I get an error.
I get the same error message for any bioconductor package.
I also get the same error when I write a DockerFile that adds a new bioconductor package based on this Docker image and run a docker build.
When I ran the same command with the same image file a few months ago, it worked fine.

> BiocManager::install("TxDb.Dmelanogaster.UCSC.dm6.ensGene")
Error: Bioconductor version cannot be validated; no internet connection?  See #troubleshooting
  section in vignette
In addition: Warning messages:
1: In file(con, "r") :
  URL 'https://bioconductor.org/config.yaml': status was 'Couldn't resolve host name'
2: In file(con, "r") :
  URL 'http://bioconductor.org/config.yaml': status was 'Couldn't resolve host name'

I have not changed the docker image or environment between last time and this time.

Have the specifications for Bioconductor changed recently??

*Ubuntu 20.04.4 LTS (on WSL2), Docker version 20.10.18

**Comment by vjcitn** [comment]
The error message seems pretty clear: there is a networking problem at your end, or perhaps the host was inaccessible for one or another reason.  At this time, I see
```
stvjc@stvjc-XPS-13-9300:~/SUBMISSIONS$ docker run -ti bioconductor/bioconductor_docker:RELEASE_3_16 bash
root@379709529c0b:/# R

R version 4.2.2 (2022-10-31) -- "Innocent and Trusting"
Copyright (C) 2022 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> BiocManager::install("TxDb.Dmelanogaster.UCSC.dm6.ensGene")
'getOption("repos")' replaces Bioconductor standard repositories, see
'?repositories' for details

replacement repositories:
    CRAN: https://packagemanager.rstudio.com/cran/__linux__/jammy/latest

Bioconductor version 3.16 (BiocManager 1.30.19), R 4.2.2 (2022-10-31)
Installing package(s) 'TxDb.Dmelanogaster.UCSC.dm6.ensGene'
also installing the dependencies ‘formatR’, ‘lambda.r’, ‘futile.options’, ‘matrixStats’, ‘futile.logger’, ‘snow’, ‘BH’, ‘MatrixGenerics’, ‘DelayedArray’, ‘assertthat’, ‘tidyselect’, ‘generics’, ‘bit’, ‘BiocParallel’, ‘Rhtslib’, ‘SummarizedExperiment’, ‘rjson’, ‘hms’, ‘dbplyr’, ‘dplyr’, ‘filelock’, ‘GenomeInfoDbData’, ‘bit64’, ‘blob’, ‘plogr’, ‘bitops’, ‘zlibbioc’, ‘XML’, ‘Rsamtools’, ‘GenomicAlignments’, ‘restfulr’, ‘progress’, ‘BiocFileCache’, ‘png’, ‘BiocGenerics’, ‘S4Vectors’, ‘IRanges’, ‘GenomeInfoDb’, ‘GenomicRanges’, ‘DBI’, ‘RSQLite’, ‘RCurl’, ‘XVector’, ‘Biostrings’, ‘BiocIO’, ‘rtracklayer’, ‘biomaRt’, ‘Biobase’, ‘KEGGREST’, ‘GenomicFeatures’, ‘AnnotationDbi’

trying URL 'https://bioconductor.org/packages/3.16/container-binaries/bioconductor_docker/src/contrib/formatR_1.12_R_x86_64-pc-linux-gnu.tar.gz'
Content type 'application/x-tar' length 149693 bytes (146 KB)
==================================================
...
```

**Comment by usu-imeg** [comment]
I ran the same thing today and it worked fine.
I do not know why.
Thanks for your help.
