### ISSUE TITLE
Update documentation to reflect no user bioc

### ISSUE THREAD

**Issue by lwaldron** [Bioconductor/bioconductor_docker#7]
Commands invoking `--user bioc` in [README.md](https://github.com/Bioconductor/bioconductor_docker/blob/master/README.md) and https://bioconductor.org/help/docker/ generate errors. Even if this is a temporary fix, I would change these to `--user rstudio` in the meantime. IMO, having one user is less prone to confusion anyways.

**Comment by nturaga** [comment]
Fixed with https://github.com/Bioconductor/bioconductor_docker/commit/211bffff16aa371d272f4d2d772f3be1631f2e51
