### ISSUE TITLE
R devel version lagging significantly

### ISSUE THREAD

**Issue by lwaldron** [Bioconductor/bioconductor_docker#8]
The current `bioconductor_docker:devel` (container ID `fcc8b104b689`) is running an r-devel from January 28:
```
R Under development (unstable) (2020-01-28 r77738)
```

The build system is running:
```
* using R Under development (unstable) (2020-03-12 r77934)
```

Is there a way to keep `bioconductor_docker:devel` more up to date with the build system?

**Comment by nturaga** [comment]
https://github.com/rocker-org/rocker-versioned/pull/198

waiting on this to be merged or fixed @lwaldron from the rocker/r-ver side of things. Once it is, the image update will cascade into bioconductor-docker. 

But I will push a local change within the day. I just need to check if everything works as expected.

**Comment by nturaga** [comment]
Coming soon as it just got merged https://github.com/rocker-org/rocker-versioned/pull/198#issuecomment-601908760 :D

**Comment by nturaga** [comment]
@lwaldron hold off on updating your docker image. There seems to be an issue with the update.

**Comment by lwaldron** [comment]
Thanks @nturaga!
