### ISSUE TITLE
README continues to mention AnVIL::

### ISSUE THREAD

**Issue by vjcitn** [Bioconductor/bioconductor_docker#80]
At least the first point is out of date?

- Make Bioconductor package binaries available to all users of the this container. Users can now install Bioconductor packages as binaries by simply doing, AnVIL::install(<character vector of packages>). This speeds up installation of Bioconductor packages by avoiding compilation.

- To see the latest status of the Bioconductor binary repository, check with AnVIL:::repository_stats().

**Comment by almahmoud** [comment]
I think the whole README is kind of out of date, especially now that we host multiple flavors. I am hoping I have time after all AnVIL pieces are released and Smorgasbord is done to stop all new development and go back and document repos from the past year as many are in need of an update. Relatedly, the container portion on bioconductor.org also needs a new pass...

**Comment by LiNk-NY** [comment]
I've updated these mentions. Updates to the rest of the `README.md` should be done in another issue.
