### ISSUE TITLE
RStudio debugger broken

### ISSUE THREAD

**Issue by Shians** [Bioconductor/bioconductor_docker#9]
The RStudio version I'm getting from the current container is 1.2.5033, it crashes whenever I try to debug.

```
f <- function() {
    1
}

debug(f)
f()
```

This has been reported as a RStudio bug https://github.com/rstudio/rstudio/issues/5888, and supposedly fixed in RStudio 1.2.5036.

**Comment by nturaga** [comment]
We'll have to wait for `rocker` to update their rstudio version for this to be fixed i'm afraid @Shians
