### ISSUE TITLE
Cannot install packages with BiocManager::install during docker build

### ISSUE THREAD

**Issue by usu-imeg** [Bioconductor/bioconductor_docker#92]
I wrote a Dockerfile to install some packages using bioconductor/bioconductor_docker as base image and built it, but when I use BiocManager::install() to install When I use BiocManager::install() to install bioconductor packages, I get an error.

> BiocManager::install('multtest', update = F)
Error: Bioconductor version cannot be validated; no internet connection?  See
  #troubleshooting section in vignette
In addition: Warning messages:
1: In file(con, "r") :
  URL 'https://bioconductor.org/config.yaml': status was 'Couldn't resolve host name'
2: In file(con, "r") :
  URL 'http://bioconductor.org/config.yaml': status was 'Couldn't resolve host name'
Execution halted

On the other hand, install.packages() installs the packages successfully.

When I did a build a few months ago using the same base image, I did not get this error.

FROM bioconductor/bioconductor_docker:RELEASE_3_16
FROM bioconductor/bioconductor_docker:RELEASE_3_17
FROM bioconductor/bioconductor_docker:RELEASE_3_18

They all have the same error.

I use Docker Engine installed on wsl2 (Ubuntu on Win).

**Comment by almahmoud** [comment]
Hey @usu-imeg , thanks for the report. It seems `bioconductor.org` is not properly resolving for you. It seems to be working as expected on my end.  Could you try it again to confirm it wasn't a temporary downtime? If not, my best guess are network restrictions of some sort preventing you from hitting the endpoint. If you run the container in the same environment, does a curl on bioconductor.org resolve?

**Comment by usu-imeg** [comment]
I just did docker build and it completed successfully with no errors.
Was this temporary downtime last time?
I did not know about the downtime.
Thanks for your advice !

**Comment by almahmoud** [comment]
I don't know of a downtime on our end, and the scripts we have tracking the server did not pick one up. I've seen this happen in VMs before when they lose internet connectivity due to network issues, but connectivity issues can happen at many levels.
