### ISSUE TITLE
Unable to start container process: exec: "/init": stat /init: no such file or directory: unknown

### ISSUE THREAD

**Issue by smartinez-yatiribio** [Bioconductor/bioconductor_docker#99]
**Describe the bug**
Using the last versions (RELEASE_3.18, RELEASE_3.17 or just latest) of images r-ver, bioconductor_docker, tidyverse... I am not able to start the container because I get an error related to the init command (see screenshot).
 
This error comes when trying docker-compose with:
```
services:
  bioc:
    container_name: tidyverse_bioc3.18
    image: "bioconductor/tidyverse:RELEASE_3_18"
  ports:
      - "8787:8787"
     .
     .
     .
```
**Screenshots**
 
![image](https://github.com/Bioconductor/bioconductor_docker/assets/80846902/df1e47b4-2699-4ede-b3b3-7744eaaeab54)

If I try to create an image based on one of those image, with FROM command in Dockerfile, then I get the error in VSCode:
![image](https://github.com/Bioconductor/bioconductor_docker/assets/80846902/e5a66fd5-4cd1-408f-af10-ae4e30e71ff9)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04

**Comment by smartinez-yatiribio** [comment]
Update on the previous comment: Now RELEASE_3_17 works with no problem, however RELEASE_3_18 is still giving me the error. I just noticed that the images in docker hub were older than they were on Friday, so I figured that you updated them to older versions.

**Comment by smartinez-yatiribio** [comment]
Using the simplest example to run the image:

![image](https://github.com/Bioconductor/bioconductor_docker/assets/80846902/2bfc2873-3d64-499f-98e9-ffcc759c54a2)

devel version of the image works, but we would appreciate if you could fix this, since we need to keep using bioconductor 3.18.

**Comment by almahmoud** [comment]
Hello @smartinez-yatiribio. I do not think this is a container issue, but please provide more information if you disagree. `3.18` containers were rebuilt 3 weeks ago, but haven't been updated recently. There was a slight bug in the devel containers briefly relating to R version mismatch (when R-devel became 4.5 and 4.4 became pre-release), but that has been fixed.

I can run the 3.18 container successfully with your command:

```
~$ docker pull bioconductor/bioconductor_docker:RELEASE_3_18
RELEASE_3_18: Pulling from bioconductor/bioconductor_docker
Digest: sha256:c2c828125d86cae96a1c77c6931d11e495939dbc43cbc520df4b5f82751fa29c
Status: Image is up to date for bioconductor/bioconductor_docker:RELEASE_3_18
docker.io/bioconductor/bioconductor_docker:RELEASE_3_18

~$ docker run -e PASSWORD=bioc -p 8787:8787 bioconductor/bioconductor_docker:RELEASE_3_18
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01_set_env: executing...
skipping /var/run/s6/container_environment/HOME
skipping /var/run/s6/container_environment/PASSWORD
skipping /var/run/s6/container_environment/RSTUDIO_VERSION
[cont-init.d] 01_set_env: exited 0.
[cont-init.d] 02_userconf: executing...
[cont-init.d] 02_userconf: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

The only scenario in which I've previously seen `exec format error` is when containers are run on the wrong chip architecture (amd64 containers on arm64 machine, or vice versa). We provide amd64 containers for all flavors, and arm64 for many but not all. If this is your case, you need to specify the correct architecture with `--platform linux/amd64` or `--platform linux/arm64` in your docker run/pull commands. In my case, using Docker for Mac, I can run either architecture as it comes with an emulator. I can however reproduce your error message by forcing `--platform linux/arm64` on a amd64-based Ubuntu VM.

Please close the issue if this resolves your problem, or follow-up with more information if not.

**Comment by smartinez-yatiribio** [comment]
Sorry for this. Yeah, it was something in my end that must have broken the RELEASE_3_18 image somehow and it wasn't enough to just purge all layers and download it again. Instead I had to uninstall the whole WSL system in my computer, and reinstall it again, purge all docker layers, and then it worked.
